const csvToExcel = require('../lib/index')


 // Add header row
 const headers = [
    { header: 'Time', key: 'Time', width: 10 },
    { header: 'V1', key: 'V1', width: 10 },
    { header: 'V2', key: 'V2', width: 10 },
    { header: 'V3', key: 'V3', width: 10 },
    { header: 'V4', key: 'V4', width: 10 },
    { header: 'V5', key: 'V5', width: 10 },
    { header: 'V6', key: 'V6', width: 10 },
    { header: 'V7', key: 'V7', width: 10 },
    { header: 'V8', key: 'V8', width: 10 },
    { header: 'V9', key: 'V9', width: 10 },
    { header: 'V10', key: 'V10', width: 10 },
    { header: 'V11', key: 'V11', width: 10 },
    { header: 'V12', key: 'V12', width: 10 },
    { header: 'V13', key: 'V13', width: 10 },
    { header: 'V14', key: 'V14', width: 10 },
    { header: 'V15', key: 'V15', width: 10 },
    { header: 'V16', key: 'V16', width: 10 },
    { header: 'V17', key: 'V17', width: 10 },
    { header: 'V18', key: 'V18', width: 10 },
    { header: 'V19', key: 'V19', width: 10 },
    { header: 'V20', key: 'V20', width: 10 },
    { header: 'V21', key: 'V21', width: 10 },
    { header: 'V22', key: 'V22', width: 10 },
    { header: 'V23', key: 'V23', width: 10 },
    { header: 'V24', key: 'V24', width: 10 },
    { header: 'V25', key: 'V25', width: 10 },
    { header: 'V26', key: 'V26', width: 10 },
    { header: 'V27', key: 'V27', width: 10 },
    { header: 'V28', key: 'V28', width: 10 },
    { header: 'Amount', key: 'Amount', width: 10 },
    { header: 'Class', key: 'Class', width: 10 }
  ];

// const headers = [
//   { header: 'id', key: 'id', width: 15 },
//   { header: 'is_active', key: 'is_active', width: 10 },
//   { header: 'created_date', key: 'created_date', width: 25 },
//   { header: 'last_modified_date', key: 'last_modified_date', width: 25 },
//   { header: 'unique_id', key: 'unique_id', width: 20 },
//   { header: 'holding_date', key: 'holding_date', width: 25 },
//   { header: 'investment_date', key: 'investment_date', width: 25 },
//   { header: 'quantity', key: 'quantity', width: 20 },
//   { header: 'average_price_per_unit', key: 'average_price_per_unit', width: 25 },
//   { header: 'total_invested_amount', key: 'total_invested_amount', width: 25 },
//   { header: 'current_price_per_unit', key: 'current_price_per_unit', width: 25 },
//   { header: 'total_current_value', key: 'total_current_value', width: 25 },
//   { header: 'total_commitment_amount', key: 'total_commitment_amount', width: 25 },
//   { header: 'total_drawdown_amount', key: 'total_drawdown_amount', width: 25 },
//   { header: 'sellable_quantity', key: 'sellable_quantity', width: 25 },
//   { header: 'total_interest_amount', key: 'total_interest_amount', width: 25 },
//   { header: 'total_return_of_capital_amount', key: 'total_return_of_capital_amount', width: 25 },
//   { header: 'total_return_on_capital_amount', key: 'total_return_on_capital_amount', width: 25 },
//   { header: 'dividend_reinvested', key: 'dividend_reinvested', width: 25 },
//   { header: 'dividend_paid', key: 'dividend_paid', width: 25 },
//   { header: 'total_income', key: 'total_income', width: 25 },
//   { header: 'accrued_interest', key: 'accrued_interest', width: 25 },
//   { header: 'absolute_profit_loss', key: 'absolute_profit_loss', width: 25 },
//   { header: 'percentage_profit_loss', key: 'percentage_profit_loss', width: 25 },
//   { header: 'xirr', key: 'xirr', width: 20 },
//   { header: 'unrealized_short_term_capital_gain', key: 'unrealized_short_term_capital_gain', width: 30 },
//   { header: 'unrealized_long_term_capital_gain', key: 'unrealized_long_term_capital_gain', width: 30 },
//   { header: 'unrealized_business_capital_gain', key: 'unrealized_business_capital_gain', width: 30 },
//   { header: 'realized_short_term_capital_gain', key: 'realized_short_term_capital_gain', width: 30 },
//   { header: 'realized_long_term_capital_gain', key: 'realized_long_term_capital_gain', width: 30 },
//   { header: 'realized_business_capital_gain', key: 'realized_business_capital_gain', width: 30 },
//   { header: 'unrealized_short_term_capital_quantity', key: 'unrealized_short_term_capital_quantity', width: 30 },
//   { header: 'unrealized_long_term_capital_quantity', key: 'unrealized_long_term_capital_quantity', width: 30 },
//   { header: 'bos_code', key: 'bos_code', width: 20 },
//   { header: 'benchmark_total_current_value', key: 'benchmark_total_current_value', width: 30 },
//   { header: 'benchmark_xirr', key: 'benchmark_xirr', width: 20 },
//   { header: 'beginning_market_value', key: 'beginning_market_value', width: 30 },
//   { header: 'beginning_market_quantity', key: 'beginning_market_quantity', width: 30 },
//   { header: 'flows', key: 'flows', width: 20 },
//   { header: 'inflows', key: 'inflows', width: 20 },
//   { header: 'outflows', key: 'outflows', width: 20 },
//   { header: 'benchmark_flows', key: 'benchmark_flows', width: 20 },
//   { header: 'benchmark_inflows', key: 'benchmark_inflows', width: 20 },
//   { header: 'benchmark_outflows', key: 'benchmark_outflows', width: 20 },
//   { header: 'absolute_return', key: 'absolute_return', width: 20 },
//   { header: 'benchmark_absolute_return', key: 'benchmark_absolute_return', width: 30 },
//   { header: 'profit', key: 'profit', width: 20 },
//   { header: 'xirr_data', key: 'xirr_data', width: 30 },
//   { header: 'benchmark_xirr_data', key: 'benchmark_xirr_data', width: 30 },
//   { header: 'states', key: 'states', width: 20 },
//   { header: 'is_zeroised', key: 'is_zeroised', width: 20 },
//   { header: 'is_sell_allowed', key: 'is_sell_allowed', width: 20 },
//   { header: 'fk_id_service_provider_account', key: 'fk_id_service_provider_account', width: 30 },
//   { header: 'fk_id_instrument', key: 'fk_id_instrument', width: 20 },
//   { header: 'fk_id_currency', key: 'fk_id_currency', width: 20 },
//   { header: 'fk_id_goal', key: 'fk_id_goal', width: 20 },
//   { header: 'product_code', key: 'product_code', width: 20 },
//   { header: 'is_held_away', key: 'is_held_away', width: 20 }
// ];

csvToExcel(headers, 'creditcard.csv', 'output.xlsx').catch(err => console.error(err));